In [1]:
%load_ext autoreload
%autoreload 2
from genfunc import *

In [2]:
F = np.array([
            [1,0,0],
            [0,1,0],
            [0,0,1],
            ])

a = level(3,1)
loss = sqeuclidean_loss(np.array([1,2,1]))
a.child = loss
loss.parent = a
a.forward(F)

5.9986154276648289

In [3]:
net = network(a,loss)
net.input_val(np.array(F))
loss_history = net.grad_desc(verbose=True)

iteration 0 / 1000: loss 5.998615427664829
iteration 100 / 1000: loss 4.019381947499418
iteration 200 / 1000: loss 2.6931933601506564
iteration 300 / 1000: loss 1.8045785570769366
iteration 400 / 1000: loss 1.2091607742860746
iteration 500 / 1000: loss 0.8102001280788617
iteration 600 / 1000: loss 0.5428759032698313
iteration 700 / 1000: loss 0.3637548750453293
iteration 800 / 1000: loss 0.24373454102912273
iteration 900 / 1000: loss 0.16331472254021165


In [4]:
np.round(a.W)

array([[ 1.,  2.,  1.]])

Yup, it got it. That was quite easy, of course. Let's do a harder one:

In [5]:
F = np.array([
            [1,0,0,0,0,0], # 1
            [0,1,0,0,0,0], # x
            [0,0,1,0,0,0], # x^2
            [1,1,1,1,1,1], # 1/(1-x)
            [1,0,-1,0,1,0], # 1/(1+x^2)
            ])

a = level(5,1)
loss = sqeuclidean_loss(np.array([3,6,-6,2,3,2]))
a.child = loss
loss.parent = a
a.forward(F)

98.04329941051499

In [6]:
net = network(a,loss)
net.input_val(F)
loss_history = net.grad_desc(verbose=True)

iteration 0 / 1000: loss 98.04329941051499
iteration 100 / 1000: loss 37.459464018226775
iteration 200 / 1000: loss 21.644723869054875
iteration 300 / 1000: loss 14.405077585310273
iteration 400 / 1000: loss 10.165478135899571
iteration 500 / 1000: loss 7.429194056080526
iteration 600 / 1000: loss 5.589241841846901
iteration 700 / 1000: loss 4.32551868940288
iteration 800 / 1000: loss 3.44386886784497
iteration 900 / 1000: loss 2.8189871131501305


In [7]:
np.round(a.W).dot(F)

array([[ 2.,  5., -5.,  1.,  3.,  1.]])

In [8]:
net = network(a,loss)
net.input_val(F)
loss_history = net.grad_desc(verbose=True)

iteration 0 / 1000: loss 2.367964853218849
iteration 100 / 1000: loss 2.035401673614263
iteration 200 / 1000: loss 1.7841168280172424
iteration 300 / 1000: loss 1.5890922178040419
iteration 400 / 1000: loss 1.4334540462471004
iteration 500 / 1000: loss 1.3057897243110943
iteration 600 / 1000: loss 1.1983520023185437
iteration 700 / 1000: loss 1.1058557955868369
iteration 800 / 1000: loss 1.0246717302251693
iteration 900 / 1000: loss 0.9522854303609513


In [9]:
np.round(a.W).dot(F)

array([[ 3.,  6., -5.,  2.,  4.,  2.]])

In [10]:
net = network(a,loss)
net.input_val(F)
loss_history = net.grad_desc(verbose=True)

iteration 0 / 1000: loss 0.8869348642102926
iteration 100 / 1000: loss 0.8273670153696908
iteration 200 / 1000: loss 0.7726745280814349
iteration 300 / 1000: loss 0.7221859588662615
iteration 400 / 1000: loss 0.6753919658355226
iteration 500 / 1000: loss 0.6318955955948791
iteration 600 / 1000: loss 0.5913787331458484
iteration 700 / 1000: loss 0.5535793971394074
iteration 800 / 1000: loss 0.5182763163947284
iteration 900 / 1000: loss 0.48527839863680755


In [11]:
np.round(a.W).dot(F)

array([[ 4.,  6., -6.,  2.,  4.,  2.]])

That one took many more iterations, but the number of parameters is so small that even doing tens of thousands of iterations won't be a problem. Using the sqeuclidean loss function, as soon as we get below 1/2 we know we've found something we can round accurately. Now let's try one it can't do.

In [12]:
F = np.array([
            [1,0,0,0,0,0], # 1
            [0,1,0,0,0,0], # x
            [0,0,1,0,0,0], # x^2
            [1,1,1,1,1,1], # 1/(1-x)
            [1,0,-1,0,1,0], # 1/(1+x^2)
            ])

a = level(5,1)
loss = sqeuclidean_loss(np.array([1,2,3,4,5,6]))
a.child = loss
loss.parent = a
a.forward(F)

91.028828107072201

In [13]:
net = network(a,loss)
net.input_val(F)
loss_history = net.grad_desc(num_iters=10000,verbose=False)

In [14]:
np.round(a.W).dot(F)

array([[ 1.,  2.,  3.,  5.,  5.,  5.]])

It'll never do better than this. In this case we'd be able to conclude that the closed form of the generating function is not a linear combination of the inputs.

We can setup multiple layers (although right now the only layer that works is multiplication by linear paramters):

In [15]:
F = np.array([
            [1,0,0,0,0,0], # 1
            [0,1,0,0,0,0], # x
            [0,0,1,0,0,0], # x^2
            [1,1,1,1,1,1], # 1/(1-x)
            [1,0,-1,0,1,0], # 1/(1+x^2)
            ])

a = level(5,8)
b = level(8,1)
loss = sqeuclidean_loss(np.array([3,6,-6,2,3,2]))
a.child = b
b.parent = a
b.child = loss
loss.parent = b
a.forward(F)

97.99997355976808

In [16]:
net = network(a,loss)
net.input_val(F)
loss_history = net.grad_desc(verbose=True)

iteration 0 / 1000: loss 97.99997355976808
iteration 100 / 1000: loss 97.84400360614269
iteration 200 / 1000: loss 40.507714960351926
iteration 300 / 1000: loss 4.227658415849827
iteration 400 / 1000: loss 1.3012428348942475
iteration 500 / 1000: loss 0.7618430509762748
iteration 600 / 1000: loss 0.4507238610771433
iteration 700 / 1000: loss 0.2613710978391413
iteration 800 / 1000: loss 0.14880173873992297
iteration 900 / 1000: loss 0.08340672780973207


In [17]:
np.round(b.W.dot(a.W.dot(F)))

array([[ 3.,  6., -6.,  2.,  3.,  2.]])

Of course this is all just basic stuff so far - linear combinations of the inputs is just the beginning. We want a flexible way to test for compositions of our inputs as well. That's coming - the framework behind this is modularized, so adding additional levels is pretty easy, you just need to tell it how to auto-diff.

One bit of weirdness - it converged much faster when we added more paramters, even though they were just as expressive as before. I think this is equivalent to messing with the learning rate, and might explain why some deeper networks seem to perform better, even though they're just as expressive (although they do have nonlinearities between parameter layers).